version: "3.9"
services:
  app:
    container_name: qpa_python
    build: ./App
    depends_on:
      - db
    entrypoint: ["bash"]

  db:
    container_name: postgres_qpa_python
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/Data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qpa_data

volumes:
  postgres_data: